apiVersion: apps/v1
kind: Deployment

metadata:
  name: model-deployment
  labels:
    app: house-price-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: house-price-model
  template:
    metadata:
      labels:
        app: house-price-model
    spec:
      containers:
      - name: house-price-model-container
        image: docker.io/ritishadhikari/house-price-model:latest
        ports:
        - containerPort: 8000
        # Add a readiness probe to ensure the container is ready to serve traffic
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "50m"
            memory: "65Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"