apiVersion: v1
kind: Secret
metadata:
  name: streamlit-secrets
type: Opaque
data:
  # Base64 encoding of 'http://model:8000/' 
  # This uses the internal Kubernetes service name and container port.
  API_URL: aHR0cDovL21vZGVsOjgwMDAv
  