apiVersion: v1
kind: Service
metadata:
  name: streamlit-external
  labels:
    app: streamlit-app
spec:
  selector:
    app: streamlit-app # Matches the deployment's labels
  ports:
  - name: http
    protocol: TCP
    port: 8501 # The port the service listens on
    targetPort: 8501 # The container port
    nodePort: 30000 # The external port on the cluster nodes
  type: NodePort # Exposes the service externally