model:
  best_model: GradientBoosting
  feature_sets:
    rfe:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '6'
    - '8'
    - '9'
    - '12'
    - '14'
  mae: 9722.979622028652
  name: house_price_model
  parameters:
    learning_rate: 0.1
    max_depth: 3
    n_estimators: 250
  r2_score: 0.9939361783683615
  target_variable: price
